app/forms/avatar.py
#! encoding=utf-8
from flask_wtf import Form
from flask_wtf.file import FileRequired, FileAllowed, FileField

class AvatarForm(Form):
    avatar = FileField(u'avatar', validators=[
        FileRequired('You need upload a image'),
        FileAllowed(['jpg', 'png'], 'You can only upload jpg or png image file')
    ])

app/forms/login.py
#! encoding=utf-8
from flask_wtf import Form
from wtforms import TextField, BooleanField, PasswordField
from wtforms.validators import DataRequired

class LoginForm(Form):
    username = TextField(u'Username', validators = [DataRequired()])
    password = PasswordField(u'Password', validators = [DataRequired()])
    remember_me = BooleanField(u'Remember me', default = False)


app/forms/passwd.py
#! encoding=utf-8
from flask_wtf import Form
from wtforms import PasswordField
from wtforms.validators import DataRequired, EqualTo

class PasswdForm(Form):
    oldpassword = PasswordField(u'Old Password', validators = [DataRequired()])
    newpassword = PasswordField(u'New Password', validators = [DataRequired()])
    confirm = PasswordField(u'Repeat New Password', validators = [
        DataRequired(),
        EqualTo('newpassword', message=u'Password do not match'),
        ])


app/forms/register.py
#! encoding=utf-8
from flask_wtf import Form
from wtforms import PasswordField, TextField
from wtforms.validators import DataRequired, EqualTo, Email

class RegisterForm(Form):
    username = TextField(u'Username', validators = [DataRequired()])
    email = TextField(u'Email', validators = [DataRequired(), Email()])
    password = PasswordField(u'Password', validators = [DataRequired()])
    repeat = PasswordField(u'Repeat', validators = [
        DataRequired(),
        EqualTo('password', message=u'Password do not match'),
    ])

app/views/frontend.py
#! encoding=utf-8
from flask import Blueprint, render_template, redirect, url_for, flash, request, g, current_app
from app.forms import LoginForm, PasswdForm, RegisterForm
from app.forms.avatar import AvatarForm
from app.models.User import User, ROLE
from app.models.score import Score
from flask.ext.login import login_user, logout_user, login_required
from app.foundation import db
import time

frontend = Blueprint('frontend', __name__, template_folder='templates')

waiting = 'waiting_users'
games = 'playing_users'

@frontend.route('/')
@login_required
def index():
    if g.user.role == ROLE['ADMIN']:
        return redirect(url_for('admin.index'))
    history = Score.query\
        .filter_by(user_id=g.user.id)\
        .order_by(Score.id.desc())\
        .limit(20)
    data = {
        "online_num": User.online_users(),
        "total_num": User.total_users(),
        "average": Score.average(g.user.id),
        "history" : history,
    }
    return render_template("frontend/index.html", **data)
@frontend.route('/login', methods = ['GET', 'POST'])
def login():
    if g.user is not None and g.user.is_authenticated():
        return redirect(url_for('.index'))
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = auth_user(username, password)
        if user is not None:
            login_user(user, remember = form.remember_me.data)
            flash(u'Welcome ' + form.username.data, 'info');
            return redirect(request.args.get("next") or url_for(".index"))
        flash(u'Username or Password is wrong', 'danger')
    return render_template("frontend/login.html", form = form)

def auth_user(username, password):
    user = User.query.filter_by(username=username).first()
    if user is None:
        return None
    else:
        return user if user.check_password(password) else None
@frontend.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for(".index"))
@frontend.route("/passwd", methods=['GET', 'POST'])
@login_required
def passwd():
    form = PasswdForm()
    if form.validate_on_submit():
        oldpassword = form.oldpassword.data
        newpassword = form.newpassword.data
        if g.user.check_password(oldpassword):
            g.user.password = User.create_password(newpassword)
            db.session.commit()
            flash(u'Password change succeed', 'success')
            return redirect(url_for(".index"))
        else:
            flash(u'Old Password is wrong', 'danger')
            form.password.data = ''
    return render_template("frontend/passwd.html", form = form)
@frontend.route("/register", methods=['GET', 'POST'])
def register():
    if g.user is not None and g.user.is_authenticated():
        return redirect(url_for('.index'))
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        email = form.email.data
        if User.query.filter_by(username=username.lower()).count():
            flash(u'Username already exists', 'danger')
        else:
            user = User(username=username, password=password, email=email, role=ROLE['NORMAL'])
            db.session.add(user)
            db.session.commit()
            login_user(user)
            flash(u'Welcome ' + form.username.data, 'info');
            return redirect(url_for(".index"))
    return render_template("frontend/register.html", form = form)

import os
from PIL import Image, ImageOps
import random
import StringIO
import shutil

@frontend.route("/avatar", methods=['GET', 'POST'])
@login_required
def avatar():
    form = AvatarForm()
    if form.validate_on_submit():
        ext = form.avatar.data.filename.split('.')[-1]
        filename = "%s_%s.%s" % (g.user.id, int(time.time()), ext)
        base = os.path.join(current_app.config['ASSET_DIR'], 'upload')
        if not os.path.isdir(base):
            os.makedirs(base)

        stream = form.avatar.data.stream
        img = StringIO.StringIO()
        shutil.copyfileobj(stream, img)
        img.seek(0)

        with open(os.path.join(base, filename), "wb") as f:
            f.write(img.read())
        img.seek(0)

        im = Image.open(img)
        size = 64,64
        avatar = ImageOps.fit(im, size, Image.ANTIALIAS)
        filename = str(g.user.id) + '.jpg'
        base = os.path.join(current_app.config['ASSET_DIR'], 'avatar')
        if not os.path.isdir(base):
            os.makedirs(base)
        avatar.save(os.path.join(base, filename))
        g.user.avatar = "/asset/avatar/%s?v=%s" % (filename, random.randint(1, 100))
        db.session.commit()
        flash(u'Avatar Change Succeed!', 'success')
        return redirect(url_for('.index'))
    return render_template("frontend/avatar.html", form=form)

app/views/team.py
#! encoding=utf-8
from flask import Blueprint, render_template, g, jsonify, request, abort
from .access import access_control
from flask.ext.login import login_required

from app.foundation import db, redis
from app.models.lock import lock, release_lock
from app.models.game import Game
import app.models.recaptcha as recaptcha

from datetime import datetime
import uuid

team = Blueprint('team', __name__)

@team.before_request
@login_required
@access_control(['NORMAL'])
def before_request():
    pass

@team.route('/')
def index():
    return render_template('team/index.html')

def generate_enqueue_result(token):
    if token:
        result = {
            "status": "SUCCESS",
            "token": token
        }
    else:
        result = {
            "status": "FAILED",
            "reason": "timeout",
        }
    return result

def register_token(token, user_id1, user_id2):
    game = Game(p1=user_id1, p2=user_id2,\
            state=Game.NEW,\
            createtime=datetime.utcnow(),
        )
    db.session.add(game)
    db.session.commit()
    game.save_map(token)
    game.init()
    pass

waiting_key = "team:waiting"
user_key = "team:userslot:%s"
lock_key = 'team_lock'

@team.route('/enqueue')
def enqueue():
    challenge = request.args.get('challenge', None)
    response = request.args.get('response', None)
    if not (challenge and response):
        result = {
            "status": "RECAPTCA",
        }
        return jsonify(result)
    if not recaptcha.validate(challenge, response):
        result = {
            "status": "RECAPTCA",
        }
        return jsonify(result)
    lock(lock_key)
    mate = redis.db.spop(waiting_key)
    result = {}
    if mate:
        #has mate
        release_lock(lock_key)
        token = uuid.uuid1().hex
        register_token(token, g.user.id, int(mate))

        mate_key = user_key % mate
        redis.db.rpush(mate_key, token)

        result = generate_enqueue_result(token)
    else:
        # start waiting
        self_key = user_key % g.user.id
        redis.db.delete(self_key)
        redis.db.sadd(waiting_key, g.user.id)
        release_lock(lock_key)
        message = redis.db.blpop(self_key, timeout=20)
        if message:
            _, token = message
        else:
            token = None
        result = generate_enqueue_result(token)

        if not token:
            redis.db.srem(waiting_key, g.user.id)

    return jsonify(result)

app/templates/frontend/avatar.html
{% extends "base.html" %}
{% import "_forms_h.html" as m %}
{% block content %}

{{g.user.avatar}}

<form method="POST" enctype="multipart/form-data" class="form-horizontal">
  {{form.hidden_tag()}}
  <div class="form-group ">
    <label class="col-lg-2 control-label" for="avatar"><span>avatar :</span></label>
    <div class="col-lg-4">
      {{form.avatar}}

      {% if form.avatar.errors %}
      <ul class="errors">
        {% for error in form.avatar.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}

    </div>
  </div>

  <div class="col-lg-offset-3 col-lg-2">
    {{ m.submit("Upload", class="btn-lg btn-primary btn-block") }}
  </div>
</form>
{% endblock %}

{% block title %}
Change Avatar
{% endblock %}

app/templates/frontend/index.html
{% extends "base.html" %}
{% import "_forms_h.html" as m %}
{% block content %}
<div class="well">
  <div> Current Online User: {{online_num}} </div>
  <div> Total User: {{total_num}} </div>

  <a class="btn btn-primary" href="{{url_for('team.index')}}"> Start game </a>
</div>

<h3> Game History <small> average score: {{average |round(1, 'floor')}} </small></h3>
<ul class="list-group">
  {% for item in history %}
  <li class="list-group-item">
  {{item.score}}
  </li>
  {% endfor %}
</ul>
{% endblock %}

{% block title %}
Online Game
{% endblock %}

app/templates/frontend/login.html
{% extends "base.html" %}
{% import "_forms_h.html" as m %}
{% block content %}
<div class="row">
	<h1> Login </h1>
	<hr />
	<form class="form-horizontal" action="" method="post" name="login">
		{{form.hidden_tag()}}
		{{ m.input(form.username, placeholder="Username") }}
		{{ m.input(form.password, placeholder="Password") }}
		{{ m.input(form.remember_me)}}
		<div class="col-lg-offset-3 col-lg-2">
			{{ m.submit("Login", class="btn-lg btn-primary btn-block") }}
		</div>
	</form>
</div>
{% endblock %}

{% block title %}
Login
{% endblock %}

app/templates/frontend/passwd.html
{% extends "base.html" %}
{% import "_forms_h.html" as m %}
{% block content %}
<div class="row">
	<h1> Change Password </h1>
	<hr />
	<form class="form-horizontal" action="" method="post" name="passwd">
		{{form.hidden_tag()}}
		{{ m.input(form.oldpassword, placeholder="Old Password") }}
		{{ m.input(form.newpassword, placeholder="New Password") }}
		{{ m.input(form.confirm, placeholder="Repeat New Password") }}
		<div class="col-lg-offset-3 col-lg-2">
			{{ m.submit("Submit", class="btn-lg btn-primary btn-block") }}
		</div>
	</form>
</div>
{% endblock %}

{% block title %}
Change Password
{% endblock %}

app/templates/frontend/register.html
{% extends "base.html" %}
{% import "_forms_h.html" as m %}
{% block content %}
<div class="row">
	<h1> Register </h1>
	<hr />
	<form class="form-horizontal" action="" method="post" name="login">
		{{form.hidden_tag()}}
		{{ m.input(form.username, placeholder="Username") }}
		{{ m.input(form.email, placeholder="Email") }}
		{{ m.input(form.password, placeholder="Password") }}
		{{ m.input(form.repeat, placeholder="Repeat your passsword") }}
		<div class="col-lg-offset-3 col-lg-2">
			{{ m.submit("Register", class="btn-lg btn-primary btn-block") }}
		</div>
	</form>
</div>
{% endblock %}

{% block title %}
Register
{% endblock %}