app/views/frontend.py
#! encoding=utf-8
from flask import Blueprint, render_template, redirect, url_for, flash, request, g, current_app
from app.forms import LoginForm, PasswdForm, RegisterForm
from app.forms.avatar import AvatarForm
from app.models.User import User, ROLE
from app.models.score import Score
from flask.ext.login import login_user, logout_user, login_required
from app.foundation import db
import time

frontend = Blueprint('frontend', __name__, template_folder='templates')

waiting = 'waiting_users'
games = 'playing_users'

@frontend.route('/')
@login_required
def index():
    if g.user.role == ROLE['ADMIN']:
        return redirect(url_for('admin.index'))
    history = Score.query\
        .filter_by(user_id=g.user.id)\
        .order_by(Score.id.desc())\
        .limit(20)
    data = {
        "online_num": User.online_users(),
        "total_num": User.total_users(),
        "average": Score.average(g.user.id),
        "history" : history,
    }
    return render_template("frontend/index.html", **data)
@frontend.route('/login', methods = ['GET', 'POST'])
def login():
    if g.user is not None and g.user.is_authenticated():
        return redirect(url_for('.index'))
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = auth_user(username, password)
        if user is not None:
            login_user(user, remember = form.remember_me.data)
            flash(u'Welcome ' + form.username.data, 'info');
            return redirect(request.args.get("next") or url_for(".index"))
        flash(u'Username or Password is wrong', 'danger')
    return render_template("frontend/login.html", form = form)

def auth_user(username, password):
    user = User.query.filter_by(username=username).first()
    if user is None:
        return None
    else:
        return user if user.check_password(password) else None
@frontend.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for(".index"))
@frontend.route("/passwd", methods=['GET', 'POST'])
@login_required
def passwd():
    form = PasswdForm()
    if form.validate_on_submit():
        oldpassword = form.oldpassword.data
        newpassword = form.newpassword.data
        if g.user.check_password(oldpassword):
            g.user.password = User.create_password(newpassword)
            db.session.commit()
            flash(u'Password change succeed', 'success')
            return redirect(url_for(".index"))
        else:
            flash(u'Old Password is wrong', 'danger')
            form.password.data = ''
    return render_template("frontend/passwd.html", form = form)
@frontend.route("/register", methods=['GET', 'POST'])
def register():
    if g.user is not None and g.user.is_authenticated():
        return redirect(url_for('.index'))
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        email = form.email.data
        if User.query.filter_by(username=username.lower()).count():
            flash(u'Username already exists', 'danger')
        else:
            user = User(username=username, password=password, email=email, role=ROLE['NORMAL'])
            db.session.add(user)
            db.session.commit()
            login_user(user)
            flash(u'Welcome ' + form.username.data, 'info');
            return redirect(url_for(".index"))
    return render_template("frontend/register.html", form = form)

import os
from PIL import Image, ImageOps
import random
import StringIO
import shutil

@frontend.route("/avatar", methods=['GET', 'POST'])
@login_required
def avatar():
    form = AvatarForm()
    if form.validate_on_submit():
        ext = form.avatar.data.filename.split('.')[-1]
        filename = "%s_%s.%s" % (g.user.id, int(time.time()), ext)
        base = os.path.join(current_app.config['ASSET_DIR'], 'upload')
        if not os.path.isdir(base):
            os.makedirs(base)

        stream = form.avatar.data.stream
        img = StringIO.StringIO()
        shutil.copyfileobj(stream, img)
        img.seek(0)

        with open(os.path.join(base, filename), "wb") as f:
            f.write(img.read())
        img.seek(0)

        im = Image.open(img)
        size = 64,64
        avatar = ImageOps.fit(im, size, Image.ANTIALIAS)
        filename = str(g.user.id) + '.jpg'
        base = os.path.join(current_app.config['ASSET_DIR'], 'avatar')
        if not os.path.isdir(base):
            os.makedirs(base)
        avatar.save(os.path.join(base, filename))
        g.user.avatar = "/asset/avatar/%s?v=%s" % (filename, random.randint(1, 100))
        db.session.commit()
        flash(u'Avatar Change Succeed!', 'success')
        return redirect(url_for('.index'))
    return render_template("frontend/avatar.html", form=form)

app/templates/_forms_h.html
{% macro render_errors(field) %}
{% if field.errors %}
<ul class="errors">
    {% for error in field.errors %}
    <li>{{ error }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endmacro %}

{% macro input(field) -%}
{% if field.type != 'HiddenField' %}
<div class="form-group {% if field.errors %}has-error{% endif %}">
    <label class="col-lg-2 control-label" for="{{ field.id }}"><span>{{ field.label.text }} :</span></label>
    <div class="col-lg-4">
        {{ field(class_="form-control", **kwargs)|safe }} {{ render_errors(field) }}
    </div>
</div>
{% else %}
	{{ field(class_="form-control", **kwargs)|safe }}
{% endif %}
{%- endmacro %}
{% macro inline_checkbox(field) -%}
	<label class="checkbox-inline">{{field}}<span> {{ field.label.text }} </span></label>
{%- endmacro %}

{% macro radio(field) -%}
<div class="form-group {% if field.errors %}has-error{% endif %}">
    <label class="col-lg-2 control-label" for="{{ field.id }}"><span>{{ field.label.text }} :</span></label>
    <div class="col-lg-4">
		{% for subfield in field %}
		<label class="checkbox-inline">
			{{ subfield }} {{subfield.label.text }}
		</label>
		{% endfor %}
	{{ render_errors(field) }}
    </div>
</div>
{%- endmacro %}


{%- macro textarea(field, value='', rows=7, cols=40) -%}
<div class="control-group {% if field.errors %}error{% endif %}">
    <label class="control-label" for="{{ field.id }}"><span>{{ field.label.text }}{%- if field.flags.required -%}*{%- endif %} :</span></label>
    <div class="controls">
	{{ field(**kwargs)|safe }} {{ render_errors(field) }}
    </div>
</div>
{%- endmacro %}

{%- macro submit(submit_title, cancel_title="", class="btn-primary") -%}
<div class="form-actions">
    <button class="btn {{ class }}" type="submit">{{ submit_title }}</button>
</div>
{%- endmacro -%}


{%- macro fields(fields, submit_title, class=None, legend=None) -%}
    <fieldset {% if class %}class="{{class}}"{% endif %}>
	{% if legend %}
	    <legend>{{legend}}</legend>
	{% endif %}

	{% for field in fields %}
	    {% if field.type == 'HiddenField' %}
		{{ field() }}
	    {% else %}
		{% if field.type == 'StringField' %}
		    {{ input(field) }}
		{% elif field.type == 'TextAreaField' %}
		    {{ textarea(field) }}
		{% endif %}
	    {% endif %}
	{% endfor %}

	{{ submit(submit_title) }}
  </fieldset>
{%- endmacro -%}




{# old _bootstrap.html code #}

{%- macro form_field_label(field) -%}
    <label for="{{ field.id }}">{{ field.label.text }}
    {%- if field.flags.required -%}*{%- endif %}</label>
{% endmacro %}

{%- macro form_field_description(field) -%}
    {% if field.description %}
        <span class="descr">{{ field.description }}</span>
    {% endif %}
{%- endmacro -%}

{%- macro form_field_errors(field) -%}
    {% if field.errors %}
    <div>
        {%- for error in field.errors -%}
        <span class="label important">{{ error }}</span>
        {%- endfor -%}
    </div>
    {% endif %}
{%- endmacro -%}

{%- macro form_field_boolean(field) -%}
	<div class="input">
		<label>
			{{ field(**kwargs) }}
			<span>{{ field.label.text }}</span>
			{{ form_field_description(field) }}
			{{ form_field_errors(field) }}
		</label>
	</div>
{%- endmacro -%}

{%- macro action_buttons(submit_title, cancel_title="Cancel", submit_class="primary") -%}
<div class="actions">
    <input type="submit" class="btn {{submit_class}}" value="{{submit_title}}">
    &nbsp;
    <button type="reset" class="btn">{{cancel_title}}</button>
</div>
{%- endmacro -%}

{%- macro form_field(field) -%}
<div class="clearfix">
    {% if field.type == 'HiddenField' %}
        {{ field() }}
    {% else %}
        {% if field.type == 'BooleanField' %}
            {{ form_field_boolean(field, **kwargs) }}
        {% else%}
            {{ form_field_label(field) }}
		<div class="input" id="{{field.id}}-div">
            {% if field.type == 'RadioField' %}
                {{ field(class='radio-group', **kwargs) }}
            {% else %}
                {{ field(**kwargs) }}
            {% endif %}
            {{ form_field_description(field) }}
            {{ form_field_errors(field) }}
		</div>
        {% endif %}
    {% endif %}
</div>
{%- endmacro -%}

{%- macro form_fields(fields, class=None, legend=None) -%}
<fieldset {% if class %}class="{{class}}"{% endif %}>
    {% if legend %}
	    <legend>{{legend}}</legend>
    {% endif %}
    {% for field in fields %}
        {% if field.type == 'HiddenField' %}
            {{ field() }}
	{% else %}
            {{ form_field(field) }}
        {% endif %}
    {% endfor %}
</fieldset>
{%- endmacro -%}

app/templates/base.html
{% extends "bootstrap_base.html" %}
{% block body_content %}
<style>
#avatar-img{
  position: absolute;
  top: -16px;
  left: 4px;
  height: 32px;
  width: 32px;
}
#avatar-outer {
  position: relative;
  display: inline-block;
  width: 36px;
  height: 5px;
}
</style>
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
<div class="container">
    <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand" href="{{url_for('frontend.index')}}"> Online Game </a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul id="navi-menu" class="nav navbar-nav">
          {% block nav %}
          {% endblock %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if g.user and g.user.is_authenticated() %}
            <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              {{g.user.username}}
              <span id="avatar-outer">
                <img id="avatar-img" src="{{g.user.avatar|default("/static/img/avatar.jpg", true)}}" />
              </span>
              <b class="caret"></b> </a>
            <ul class="dropdown-menu">
                <li><a href="{{url_for('frontend.avatar')}}"> Change Avatar  </a></li>
                <li><a href="{{url_for('frontend.passwd')}}"> Change Password </a></li>
                <li><a href="{{url_for('frontend.logout')}}"> Logout </a></li>
            </ul>
            {% else %}
            <li> <a href="{{url_for('frontend.login')}}"> Login </a> </li>
            <li> <a href="{{url_for('frontend.register')}}"> Register </a> </li>
            {% endif %}

        </div>
    </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
    <div class="container">
        <div id="alert">
            {% for category, message in messages %}
            <div class="alert alert-{{category}}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    {% endwith %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% endblock %}

app/templates/bootstrap_base.html
<!DOCTYPE html>
<html{% block html_attribs %} lang="en"{% endblock html_attribs %}>
{%- block html %}
  <head>
  {%- block head %}
    <meta charset="utf-8">
    <title>{% block title %}{{title}}{% endblock title %}</title>
    {%- block meta %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    {%- endblock meta %}
    <script src="{{url_for('static', filename='js/lib/jquery-2.0.3.min.js')}}"></script>
    {%- block style %}
    <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
	<!--
    <link href="{{url_for('static', filename='css/font-awesome.min.css')}}" rel="stylesheet">
	-->
    {%- block style_navbar_padding %}
    <style>
      body {
        padding-top: 60px;
      }
    </style>
    {%- endblock style_navbar_padding %}
    {%- endblock style %}

    {%- block favicons %}
    {%- endblock favicons %}


  {%- endblock head %}
  </head>

  <body>
  {%- block body %}
    {%- block body_content %}
    {%- endblock body_content %}
    {%- block bootstrap_js_bottom %}
    <script src="/static/js/lib/bootstrap.min.js"></script>
    {%- endblock bootstrap_js_bottom %}
  {%- endblock body %}
  </body>
  <!-- Font Awesome is licensed CC-BY-3.0: http://fortawesome.github.com/Font-Awesome -->
{%- endblock html %}
</html>